// Menu data
const menuItems = [
  {
    id: 1,
    name: "Classic Burger",
    description: "Juicy beef patty with lettuce, tomato, and special sauce",
    price: 12.99,
    category: "Mains",
    image: "https://source.unsplash.com/1200x800/?burger,fries&sig=1",
  },
  {
    id: 2,
    name: "Margherita Pizza",
    description: "Fresh mozzarella, basil, and tomato sauce on thin crust",
    price: 14.99,
    category: "Mains",
    image: "https://source.unsplash.com/1200x800/?margherita,pizza&sig=2",
  },
  {
    id: 3,
    name: "Sushi Platter",
    description: "Assorted fresh sushi rolls with wasabi and ginger",
    price: 22.99,
    category: "Mains",
    image: "https://source.unsplash.com/1200x800/?sushi,platter&sig=3",
  },
  {
    id: 4,
    name: "Pasta Carbonara",
    description: "Creamy Italian pasta with bacon and parmesan",
    price: 16.99,
    category: "Mains",
    image: "https://source.unsplash.com/1200x800/?pasta,carbonara&sig=4",
  },
  {
    id: 5,
    name: "Chicken Tacos",
    description: "Three soft tacos with grilled chicken and fresh salsa",
    price: 11.99,
    category: "Mains",
    image: "https://source.unsplash.com/1200x800/?chicken,tacos&sig=5",
  },
  {
    id: 6,
    name: "Caesar Salad",
    description: "Crisp romaine lettuce with Caesar dressing and croutons",
    price: 9.99,
    category: "Salads",
    image: "https://source.unsplash.com/1200x800/?caesar,salad&sig=6",
  },
  {
    id: 7,
    name: "Chocolate Cake",
    description: "Rich chocolate cake with ganache frosting",
    price: 7.99,
    category: "Desserts",
    image: "https://source.unsplash.com/1200x800/?chocolate,cake&sig=7",
  },
  {
    id: 8,
    name: "Fresh Lemonade",
    description: "Homemade lemonade with fresh lemons",
    price: 4.99,
    category: "Drinks",
    image: "https://source.unsplash.com/1200x800/?lemonade,drink&sig=8",
  },
  {
    id: 9,
    name: "Garlic Bread Bites",
    description: "Toasted garlic butter bread with herbs and parmesan",
    price: 6.49,
    category: "Starters",
    image: "https://source.unsplash.com/1200x800/?garlic,bread&sig=9",
  },
  {
    id: 10,
    name: "Loaded Nachos",
    description: "Crispy nachos with cheese, jalapeno, salsa, and sour cream",
    price: 8.99,
    category: "Starters",
    image: "https://source.unsplash.com/1200x800/?nachos&sig=10",
  },
  {
    id: 11,
    name: "Tofu Buddha Bowl",
    description: "Roasted tofu, brown rice, veggies, and sesame dressing",
    price: 13.49,
    category: "Vegan",
    image: "https://source.unsplash.com/1200x800/?tofu,bowl&sig=11",
  },
  {
    id: 12,
    name: "Quinoa Power Salad",
    description: "Quinoa, avocado, chickpeas, greens, and citrus dressing",
    price: 11.99,
    category: "Salads",
    image: "https://source.unsplash.com/1200x800/?quinoa,salad&sig=12",
  },
  {
    id: 13,
    name: "BBQ Chicken Pizza",
    description: "Smoky BBQ sauce, grilled chicken, onions, and mozzarella",
    price: 17.49,
    category: "Mains",
    image: "https://source.unsplash.com/1200x800/?bbq,chicken,pizza&sig=13",
  },
  {
    id: 14,
    name: "Family Combo Pack",
    description: "2 mains, 2 sides, and 2 drinks at a special combo price",
    price: 29.99,
    category: "Combos",
    image: "https://source.unsplash.com/1200x800/?family,meal,table&sig=14",
  },
  {
    id: 15,
    name: "Iced Coffee",
    description: "Cold brewed coffee served over ice with milk option",
    price: 5.49,
    category: "Drinks",
    image: "https://source.unsplash.com/1200x800/?iced,coffee&sig=15",
  },
  {
    id: 16,
    name: "Strawberry Cheesecake",
    description: "Creamy baked cheesecake with strawberry topping",
    price: 8.49,
    category: "Desserts",
    image: "https://source.unsplash.com/1200x800/?strawberry,cheesecake&sig=16",
  },
];
